In [1]:
import numpy as np

In [2]:
def possible_placements(y, x):
    row_possible = set(range(1, 10)) - set(puzzle[y, :])
    col_possible = set(range(1, 10)) - set(puzzle[:, x])
    box_possible = set(range(1, 10)) - set(puzzle[3*int(y / 3):3*(int(y / 3)+1), 3*int(x / 3):3*(int(x / 3)+1)].ravel())
    return row_possible & col_possible & box_possible

In [3]:
puzzle = np.array(
[
[0, 2, 0, 0, 0, 0, 0, 0, 0],
[0, 0, 0, 6, 0, 0, 0, 0, 3],
[0, 7, 4, 0, 8, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 3, 0, 0, 2],
[0, 8, 0, 0, 4, 0, 0, 1, 0],
[6, 0, 0, 5, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 0, 7, 8, 0],
[5, 0, 0, 0, 0, 9, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 4, 0],
]
)

In [4]:
def solver(grid):
    for row in range(puzzle.shape[1]):
        for col in range(puzzle.shape[0]):
            if puzzle[row, col] == 0:
                for i in possible_placements(row, col):
                    grid[row, col] = i
                    ret_grid = solver(grid)
                    if ret_grid is not None:
                        return ret_grid
                    grid[row, col] = 0
                return
    return grid

In [5]:
print(solver(puzzle))

[[1 2 6 4 3 7 9 5 8]
 [8 9 5 6 2 1 4 7 3]
 [3 7 4 9 8 5 1 2 6]
 [4 5 7 1 9 3 8 6 2]
 [9 8 3 2 4 6 5 1 7]
 [6 1 2 5 7 8 3 9 4]
 [2 6 9 3 1 4 7 8 5]
 [5 4 8 7 6 9 2 3 1]
 [7 3 1 8 5 2 6 4 9]]
